apiVersion: v1
kind: ConfigMap
metadata:
  name: sound-scout-config
  namespace: default
data:
  BACKEND_PORT: "5000"
  WORKER_PORT: "4000"
  AI_PORT: "8000"
  WHATSAPP_WORKER_URL: "http://sound-scout-whatsapp-worker:4000"
  MAIN_BACKEND_URL: "http://sound-scout-backend:5000"
  AI_SERVICE_URL: "http://sound-scout-ai:8000/api/generate"
